### ISSUE TITLE
Composer version

### ISSUE THREAD

**Issue by miladrahimi** [sallar/jDateTime#24]
سلام و خسته نباشید.
با توجه به اینکه خیلی پکیج مفیدی هستش حیف هستش که نکات ریز استاندارد سازی رو رعایت نکرده باشید.
هیچ نسخه از پکیج تو سایت پکیجیست کمپوزر ثبت نکردید و فقط باید نسخه مستر رو دانلود کرد.
بهتره توی سایت پکیجیست توی صفحه مربوطه اپدیت کنید تا نسخه اخر موجود در گیتهاب به پکیجیت منتقل بشه اگه توکن پکیجیت رو هم توی تنظیمات پکیج توی گیتهاب اضافه کنید آپدیت ها بصورت خودکار اعمال میشن.

مناسب اینه که نسخه اخر توی صفحه 
https://packagist.org/packages/sallar/jdatetime
موجود باشه نه نسخه مستر و از طریق خط فرمان بشه با این دستور نصب کرد:
composer require sallar/jdatetime
نه با این:
composer require "sallar/jdatetime":"dev-master"

باز هم تشکر می کنم بابت ساخت این پکیج.

**Comment by sallar** [comment]
@miladrahimi سلام
ممنون
متاسفانه چون من دیگه با پی‌اچ‌پی برنامه نمی‌نویسم فرصت زیادی ندارم که روی این پروژه وقت بذارم. اون موقع هم که این رو نوشته بودم کمپوزر خیلی محبوب نبود.
اگر خودت فرصت کردی یه نگاهی بهش بندازی ممنون میشم کمک کنی.

سالار

**Comment by miladrahimi** [comment]
اما الان برنامه نویس های پی اچ پی از پکیج شما استفاده می کنن.
خوشحال میشم کمک کنم

توی تنظیمات پروژه گزینه
Collaborators
منو ادد کنید
miladrahimi
و پسورد اکانت خودتون توی
packagist.org
رو هم می خوام تا پروژه روی همون قبلی اپدیت کنم
info@miladrahimi.com

با تشکر.
