### ISSUE TITLE
New version available (My fork)

### ISSUE THREAD

**Issue by vsg24** [sallar/jDateTime#30]
I made some changes and improved jDateTime class. It's [available here as jDateTimePlus ](https://github.com/VSG24/jDateTimePlus)if anybody is interested. I also created a higher level abstraction of jDateTimePlus which is extremely easy to use and it's reliable. I highly recommend using that. It's available here as [EasyDateTime](https://github.com/VSG24/EasyDateTime).

**Comment by p3ym4n** [comment]
Take a look at this :
[https://packagist.org/packages/p3ym4n/jdate](https://packagist.org/packages/p3ym4n/jdate)
