### ISSUE TITLE
Deprecated syntax notice on PHP 7.4.3

### ISSUE THREAD

**Issue by akalantari** [sallar/jDateTime#38]
In static function `getdate` a notice is shown as is described below:
Deprecated: Array and string offset access syntax with curly braces is deprecated in `sallar/jdatetime/jdatetime.class.php` on line 467

The line uses curly braces to access the first letter in `$timestamp`, and it should change to use brackets instead.

**Comment by sallar** [comment]
Hi. This package deprecated.
